SHELL=/bin/bash
summary/all.tex: gen
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Transketolase'(2), 'Transaldolase'(3)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 25}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/001_f_25_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_25, 0}}{out/015_dg_25_11100_f_25_0_filt}{\texttt{out/015\_dg\_25\_11100\_f\_25\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transketolase'(2), 'Transaldolase'(3)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 41}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/017_f_41_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_41, 0}}{out/035_dg_41_11100_f_41_0_filt}{\texttt{out/035\_dg\_41\_11100\_f\_41\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Transketolase'(2), 'Transaldolase'(3), 'Aldolase'(4)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 47}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/037_f_47_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_47, 0}}{out/047_dg_47_11100_f_47_0_filt}{\texttt{out/047\_dg\_47\_11100\_f\_47\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Transketolase'(2), 'Transaldolase'(3), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 48}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/049_f_48_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_48, 0}}{out/071_dg_48_11100_f_48_0_filt}{\texttt{out/071\_dg\_48\_11100\_f\_48\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transketolase'(2), 'Transaldolase'(3), 'Aldolase'(4)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 56}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/073_f_56_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_56, 0}}{out/091_dg_56_11100_f_56_0_filt}{\texttt{out/091\_dg\_56\_11100\_f\_56\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transketolase'(2), 'Transaldolase'(3), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 57}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/093_f_57_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_57, 0}}{out/123_dg_57_11100_f_57_0_filt}{\texttt{out/123\_dg\_57\_11100\_f\_57\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transketolase'(2), 'Aldolase'(4), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 58}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/125_f_58_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_58, 0}}{out/145_dg_58_11100_f_58_0_filt}{\texttt{out/145\_dg\_58\_11100\_f\_58\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transaldolase'(3), 'Aldolase'(4), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 59}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/147_f_59_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_59, 0}}{out/165_dg_59_11100_f_59_0_filt}{\texttt{out/165\_dg\_59\_11100\_f\_59\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Transketolase'(2), 'Transaldolase'(3), 'Aldolase'(4), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 60}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/167_f_60_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_60, 0}}{out/183_dg_60_11100_f_60_0_filt}{\texttt{out/183\_dg\_60\_11100\_f\_60\_0\_filt}}' >> summary/all.tex
	echo '\summarySection{Enzymes: ['Aldose-Ketose \textless{}-'(0), 'Aldose-Ketose -\textgreater{}'(1), 'Transketolase'(2), 'Transaldolase'(3), 'Aldolase'(4), 'Phophohydrolase'(5)] }' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 62}' >> summary/all.tex
	echo '\summarySubsection{Solution 0}' >> summary/all.tex
	echo '\summarySubsubsection{Overall Data}' >> summary/all.tex
	echo '\input{out/185_f_62_0_listing.tex}' >> summary/all.tex
	echo '\summaryFlowFiltered{\texttt{dgFlow\_62, 0}}{out/221_dg_62_11100_f_62_0_filt}{\texttt{out/221\_dg\_62\_11100\_f\_62\_0\_filt}}' >> summary/all.tex
summary.pdf: summary/all.tex
	mod_post --mode compileSummary
include summary/MakefileImpl
include summary/MakefileDep
include summary/MakefileAllTarget
include summary/MakefileClean
